#Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.

num = int(input('Digite um número, por favor: '))
print('=============')
print('{:2} x {} = {}' .format(1, num, num*1))
print('{:2} x {} = {}' .format(2, num, num*2))
print('{:2} x {} = {}' .format(3, num, num*3))
print('{:2} x {} = {}' .format(4, num, num*4))
print('{:2} x {} = {}' .format(5, num, num*5))
print('{:2} x {} = {}' .format(6, num, num*6))
print('{:2} x {} = {}' .format(7, num, num*7))
print('{:2} x {} = {}' .format(8, num, num*8))
print('{:2} x {} = {}' .format(9, num, num*9))
print('{:2} x {} = {}' .format(10, num, num*10))
print('=============')
